# -*- coding: utf-8 -*-
"""c2p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AW3pYlL40OVxwYFXHqmijYKEMw3_rNrY

Problem Statement

Suppose a newly born pair of rabbits, one male and one female, are
put in a field. Rabbits can mate at the age of one month so that at the end of its second month, a female has produced another pair of
rabbits. Suppose that our rabbits never die and that the female always produces one new pair every month from the second month. Develop a program to show a table containing the number of pairs of
rabbits in the first N months

"""
# Function to return a list with N fibbonacci numbers


def fib(N):
    Flist = [0, 1, 1]
    a = 1
    b = 1
    for i in range(1, N):
        t = a
        b = a + b
        a = b
        b = t
        Flist.append(a)
    return Flist

# Function to make a table for N months


def Pair_Details(N):
    l1 = fib(N)
    print("+", "-"*5, "+", "-"*6, "+")
    print("| Month | Pairs  |")
    print("+", "-"*5, "+", "-"*6, "+")
    for i in range(1, N+1):
        print("|%6d | %6d |" % (i, l1[i]))
    print("+", "-"*5, "+", "-"*6, "+")


# main function
def main():
    Nr = int(input("Enter the number of rabbits : "))
    print("Table\n\n")
    Pair_Details(Nr)
