# -*- coding: utf-8 -*-
"""c2p5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bpaZQCgr-BmUVgMu3fqt6i9ObggHAEph

Write a program to create a parent class, 3DShapes, with methods
printVolume() and printArea(), which prints the Volume and Area,
respectively. Create classes Cylinder and Sphere by inheriting
3DShapes class. Using these child classes, calculate and print the
volume and area of a cylinder and sphere.
"""

# Declaring Base class 3D shapes


class Shapes3D:
    def printVolume(self):
        print("Volume  : ", self.volume)

    def printArea(self):
        print("Surface Area : ", self.area)

# Deriving Cylinder and Sphere classes


class Cylinder(Shapes3D):
    def __init__(self, r, h):
        self.r = r
        self.h = h
        self.area = (2*3.14*r*h) + (2*3.14*r*r)
        self.volume = (3.14*r*r*h)


class Sphere(Shapes3D):
    def __init__(self, r):
        self.r = r
        self.area = 4*3.14*r*r
        self.volume = (4/3)*3.14*(r**3)


# main function

print("For cylinder : ")
rC = int(input("Enter the radius : "))
hC = int(input("Enter the height : "))
C1 = Cylinder(rC, hC)
C1.printVolume()
C1.printArea()


print("For Sphere : ")
rS = int(input("Enter the radius : "))
S1 = Sphere(rS)
S1.printVolume()
S1.printArea()
