# -*- coding: utf-8 -*-
"""c1p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWM6Zyi7gG5Qm1jzku61v5eu5fu98kTx

# Question 1

```
Develop a program to read a four-digit number and find its
a. Sum of digits
b. Reverse
c. Difference between the product of digits at the odd position
and the product of digits at the even position.
```
"""


def sum_of_digits(N):
    #Extraction of digits
    d1 = N%10
    d2 =(N//10)%10
    d3 = (N//100)%10
    d4 = (N//1000)%10
    #To get sum of digits
    sum = d1+d2+d3+d4
    return sum

def reverse(N):
    d1 = N%10
    d2 =(N//10)%10
    d3 = (N//100)%10
    d4 = (N//1000)%10
    # To Find the reverse
    rev = d4 + d3*10 + d2*100 + d1*1000
    return rev

# To find Difference between the product of digits at the odd position
# and the product of digits at the even position.
def odd_even_pdt_diff(N):
    d1 = N%10
    d2 =(N//10)%10
    d3 = (N//100)%10
    d4 = (N//1000)%10
    diff = (d2*d4) - (d1*d3)
    return diff

def main():
    N = int(input("Enter a 4 digit number: "))
    sum = sum_of_digits(N)
    print("Sum of Digits = ",sum)
    rev = reverse(N)
    print("Reverse = ",rev)
    diff = odd_even_pdt_diff(N)
    print("Difference of digit product at the odd and position = ") 
    print(diff)

if __name__ == "__main__":
    main()