# -*- coding: utf-8 -*-
"""c2p3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12l7BTkmr6ES1KdZDxxZIjs2OnWDE-gyd

Read the file 'iris.json' as a text file :
1. Create a list having each line of the file as an element
2. Convert it into a list of dictionary objects.
3. Show the details of all flowers whose species is
"setosa".
4. Print the minimum petal area and max sepal area in
each species
5. Sort the list of dictionaries according to the total area
are sepal and petal.
"""

#To open the file and read its data
f = open("iris.json","r")
str_data = f.read()

#List having each line of the file as an element
Line_list = str_data.split("\n")
f.close()

#Conversion into a list of dictionary objects
f = open("iris.json","r")
import json
data = json.load(f)
f.close()

#Show the details of all flowers whose species is "setosa"
print("details of all flowers whose species is 'setosa' \n")
print("sepalLength\tsepalWidth\tpetalLength\tpetalWidth")
for i in data:
  if i['species'] == 'setosa':
    print(i['sepalLength'],"\t\t",i['sepalWidth'],"\t\t",i['petalLength'],"\t\t",i['petalWidth'])

#Print the minimum petal area and max sepal area in each species
species = []
#Collecting Unique Species
for j in data:
  if j['species'] not in species:
    species.append(j['species'])

Mpa = list()
Msa = list()
ctrl1 = 0
for Species in species:
  Mpa.append(100)
  Msa.append(0)
  for j in data:
    if j['species'] == Species:
      if (j['petalLength'] * j['petalWidth']) < Mpa[ctrl1]:
        Mpa[ctrl1] = round(j['petalLength'] * j['petalWidth'],2) 
      if (j['sepalLength'] * j['sepalWidth']) > Msa[ctrl1]:
        Msa[ctrl1] = round(j['sepalLength']* j['sepalWidth'],2)
  ctrl1+=1
print("\n\n")
print("Species - MinPetalArea - MaxSepalArea\n")
for i in range(0,3):
  print(species[i]," - ",Mpa[i]," - ",Msa[i],"\n")
#Sort the list of dictionaries according to the total area are sepal and petal

#To create a new attribute Total Area 
for i in data:
  x = 0
  TArea = i['sepalLength']*i['sepalWidth'] + i['petalLength']*i['petalWidth']
  i['TotalArea'] = round(TArea,2)

#TO sort the list of Dictionaries
for _ in data:
  for i in range(0,len(data)-1) :
    d1 = data[i]
    d2 = data[i+1]
    if d1['TotalArea'] > d2['TotalArea']:
      data[i],data[i+1] = data[i+1],data[i]

#Print the Total Area as a Table
print("sepalLength\tsepalWidth\tpetalLength\tpetalWidth\tTotalArea")      
for i in data:
    print(i['sepalLength'],"\t\t",i['sepalWidth'],"\t\t",i['petalLength'],end = " ")
    print("\t\t",i['petalWidth'],"\t\t",i['TotalArea'])

